### ISSUE TITLE
role of 'intent'

### ISSUE THREAD

**Issue by acthp** [justinwoo/react-rxjs-flow#2]
I'm trying to understand all the levels of indirection between the event (user clicks button, etc.), and the update of the state. It goes
- The async event is bound to a function, this.handleIncrement
- ... which invokes a second function. Intent.incrementCounter
- ... which reifies the event as {key: 'INCREMENT_COUNTER'}, and puts it on a stream
- ... that is consumed by the model, which evaluates the event by calling incrementCounter

What does this buy you? It seems like the intent is a complicated pass-through. What is an example of when the intent is adding some functionality?

**Comment by justinwoo** [comment]
yeah, how i originally did it just mirrors keyed events in flux and kind of sucks. it lets the model subscribe to a single stream for the intent. this branch uses separate subjects per intent: https://github.com/justinwoo/react-rxjs-flow/blob/each-intent-subject/src/intent.js

my intents are usually just dumb pass-throughs, but  i've started just handling the virtual DOM events directly in the intents and make sure my model observers are as dumb as possible (also components get complicated so anything related to my application goes directly to intents).
