### ISSUE TITLE
class / extends

### ISSUE THREAD

**Issue by Cmdv** [justinwoo/react-rxjs-flow#3]
Hi, great implementation just had a little play around and easily managed to implement a decrease button in minutes.

My only worry is the implementation of Class:
https://medium.com/javascript-scene/how-to-fix-the-es6-class-keyword-2d42bb3f4caf

I would change Root to:

`var React = require('react');`
`var Intent = require('../intent');`
`var Root = React.createClass({`

  `handleIncrement: function () {`
    `Intent.incrementCounter();`
 `},`
  `render() {`
   `console.log('props', this.props);`
    `return (`
     `<div>`
        `<h1>Hello</h1>`

```
    `<p>counter: {this.props.counter}</p>`
    `<button onClick={this.handleIncrement}>+1</button>`
  `</div>`
`);`
```

  `}`
`});`

`module.exports = Root;`

Obviously this is down to personal taste :)

**Comment by justinwoo** [comment]
yeah, i still use both the factory function and ES6 classes. the main thing is that i usually try to not mix in behaviors from multiple sources and just try to share pure functions between my components, so using ES6 classes doesn't bother me too much.

this is how i'm using ES6 classes now, where i only do single inheritance: https://gist.github.com/justinwoo/7ff9355fbfa358ea6f61

though, auto-bound functions in the createClass factory function is pretty nice, so i might go back to just using that like you suggest. if anything, the only problem with the createClass method is that it exposes a very slow, crappy mixins API when you really could use Object.assign and your own merging strategy for creating components.

**Comment by Cmdv** [comment]
Ah yeah that makes sense, just have to be careful I guess. 

I'm not a 100% but I do think that createClass might become obsolete in which case will have to have another workaround. I'm sure there will be a good solution. Sure I saw somewhere someone using "createFactory" but could be very wrong as my react isn't that strong. 

There just isn't that many examples out there at the moment but like everything it's trial and error.

I'm going to try implement api calls using RxJS in my stores, maybe make a predictive search bar or something like that will see if I get the time. But your implementation has really helped thank you.
