### ISSUE TITLE
Adding react-router...

### ISSUE THREAD

**Issue by Cmdv** [justinwoo/react-rxjs-flow#6]
Hi, I'm experimenting with your repo ([here](https://github.com/Cmdv/React-RxJS/tree/feature/react-router)) as I'm trying to extend it by adding more options. If you'd prefer me to fork from here I will.

Anyways on the branch linked above I'm trying to use React-router to do my routing.

``` javascript
Router.run(routes, function (Handler) {
  Model.subject.subscribe((appState) => {
    console.log(appState); //gives correct state
    React.render(
      <Handler {...appState}/>, // appState doesn't seem go through
      document.getElementById('app')
    );
  });
});
```

do you have a clue how the `appState` could be passed into the props?!?!

I'm also going to be trying to make a simple Auth and some sort of JSON api, just trying to add some real life implementations :smile:

**Comment by justinwoo** [comment]
I remember being annoyed by this, SO thread: http://stackoverflow.com/questions/27864720/react-router-pass-props-to-handler-component

they don't let you pass props into the handler, so you'll have to work around it somehow.

i don't usually use react-router in my own projects though. the most i usually do is hook up to the hash location.

**Comment by Cmdv** [comment]
I posted this issue on react-router [here](https://github.com/rackt/react-router/issues/1230) and BerkeleyTrue the creator of Thundercats.js came back with some great advice with the use of  `combineLatest` it doesn't fully fix it yet but I'm going to do a little more experimentation as it looks like it's going in the right direction.

**Comment by Cmdv** [comment]
just to let you know I managed to work it out if you look [here](https://github.com/Cmdv/React-RxJS/blob/master/src/index.js) :)

**Comment by justinwoo** [comment]
huh... so you _can_ pass in props to the root handler?

**Comment by Cmdv** [comment]
yeah seems that way and you then have the `this.props` available on all your routes. I've now added styling and a counter in the navigation to show off the state a little more.
